<?php
/**
 * IngestionState
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Interop Data API
 *
 * Interop Data APIs provide access to the data objects and events from Interop Cloud repositories and Integration repositories
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kimono\Model;

/**
 * IngestionState Class Doc Comment
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IngestionState
{
    /**
     * Possible values of this enum
     */
    const UNSPECIFIED = 'unspecified';
    const PREPARING = 'preparing';
    const SCHEDULED = 'scheduled';
    const EXECUTING = 'executing';
    const SUCCESS = 'success';
    const FAILED = 'failed';
    const CANCELLED = 'cancelled';
    const TIMEOUT = 'timeout';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNSPECIFIED,
            self::PREPARING,
            self::SCHEDULED,
            self::EXECUTING,
            self::SUCCESS,
            self::FAILED,
            self::CANCELLED,
            self::TIMEOUT,
        ];
    }
}


