<?php
/**
 * Task
 *
 * PHP version 5
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Interop Data API
 *
 * Interop Data APIs provide access to the data objects and events from Interop Cloud repositories and Integration repositories
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kimono\Model;

use ArrayAccess;
use Kimono\ObjectSerializer;

/**
 * Task Class Doc Comment
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Task implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Task';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'schema' => 'string',
        'syncEvent' => '\Kimono\Model\SyncEvent',
        'dataEvent' => '\Kimono\Model\DataEvent',
        'lifecycleEvent' => '\Kimono\Model\LifecycleEvent'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'schema' => null,
        'syncEvent' => null,
        'dataEvent' => null,
        'lifecycleEvent' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'schema' => 'schema',
        'syncEvent' => 'sync_event',
        'dataEvent' => 'data_event',
        'lifecycleEvent' => 'lifecycle_event',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'schema' => 'setSchema',
        'syncEvent' => 'setSyncEvent',
        'dataEvent' => 'setDataEvent',
        'lifecycleEvent' => 'setLifecycleEvent',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'schema' => 'getSchema',
        'syncEvent' => 'getSyncEvent',
        'dataEvent' => 'getDataEvent',
        'lifecycleEvent' => 'getLifecycleEvent',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['schema'] = isset($data['schema']) ? $data['schema'] : null;
        $this->container['syncEvent'] = isset($data['syncEvent']) ? $data['syncEvent'] : null;
        $this->container['dataEvent'] = isset($data['dataEvent']) ? $data['dataEvent'] : null;
        $this->container['lifecycleEvent'] = isset($data['lifecycleEvent']) ? $data['lifecycleEvent'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets schema
     *
     * @return string|null
     */
    public function getSchema()
    {
        return $this->container['schema'];
    }

    /**
     * Sets schema
     *
     * @param string|null $schema TBD
     *
     * @return $this
     */
    public function setSchema($schema)
    {
        $this->container['schema'] = $schema;

        return $this;
    }

    /**
     * Gets syncEvent
     *
     * @return \Kimono\Model\SyncEvent|null
     */
    public function getSyncEvent()
    {
        return $this->container['syncEvent'];
    }

    /**
     * Sets syncEvent
     *
     * @param \Kimono\Model\SyncEvent|null $syncEvent syncEvent
     *
     * @return $this
     */
    public function setSyncEvent($syncEvent)
    {
        $this->container['syncEvent'] = $syncEvent;

        return $this;
    }

    /**
     * Gets dataEvent
     *
     * @return \Kimono\Model\DataEvent|null
     */
    public function getDataEvent()
    {
        return $this->container['dataEvent'];
    }

    /**
     * Sets dataEvent
     *
     * @param \Kimono\Model\DataEvent|null $dataEvent dataEvent
     *
     * @return $this
     */
    public function setDataEvent($dataEvent)
    {
        $this->container['dataEvent'] = $dataEvent;

        return $this;
    }

    /**
     * Gets lifecycleEvent
     *
     * @return \Kimono\Model\LifecycleEvent|null
     */
    public function getLifecycleEvent()
    {
        return $this->container['lifecycleEvent'];
    }

    /**
     * Sets lifecycleEvent
     *
     * @param \Kimono\Model\LifecycleEvent|null $lifecycleEvent lifecycleEvent
     *
     * @return $this
     */
    public function setLifecycleEvent($lifecycleEvent)
    {
        $this->container['lifecycleEvent'] = $lifecycleEvent;

        return $this;
    }


    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


