<?php
/**
 * IngestionState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Interop Data API
 *
 * Interop Data APIs provide access to the data objects and events from Interop Cloud repositories and Integration repositories
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.3.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Kimono\Model;
use \Kimono\ObjectSerializer;

/**
 * IngestionState Class Doc Comment
 *
 * @category Class
 * @package  Kimono
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class IngestionState
{
    /**
     * Possible values of this enum
     */
    public const UNSPECIFIED = 'unspecified';

    public const PREPARING = 'preparing';

    public const SCHEDULED = 'scheduled';

    public const EXECUTING = 'executing';

    public const SUCCESS = 'success';

    public const FAILED = 'failed';

    public const CANCELLED = 'cancelled';

    public const TIMEOUT = 'timeout';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNSPECIFIED,
            self::PREPARING,
            self::SCHEDULED,
            self::EXECUTING,
            self::SUCCESS,
            self::FAILED,
            self::CANCELLED,
            self::TIMEOUT
        ];
    }
}


